// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250405004655_UpdatedSeedData")]
    partial class UpdatedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 52,
                            Email = "Colt_Kris80@example.com",
                            Name = "Amos Gerhold"
                        },
                        new
                        {
                            Id = 2,
                            Age = 44,
                            Email = "Rory.Konopelski@example.org",
                            Name = "Adell Ebert"
                        },
                        new
                        {
                            Id = 3,
                            Age = 48,
                            Email = "Maximilian.Hoppe10@example.com",
                            Name = "Larue Graham"
                        },
                        new
                        {
                            Id = 4,
                            Age = 36,
                            Email = "Edna30@example.com",
                            Name = "Milford Kerluke"
                        },
                        new
                        {
                            Id = 5,
                            Age = 65,
                            Email = "Florine_Morissette16@example.org",
                            Name = "Jan Parisian"
                        },
                        new
                        {
                            Id = 6,
                            Age = 70,
                            Email = "Manuel_Romaguera@example.org",
                            Name = "Alejandrin Gaylord"
                        },
                        new
                        {
                            Id = 7,
                            Age = 34,
                            Email = "Consuelo6@example.com",
                            Name = "Dillan Schinner"
                        });
                });

            modelBuilder.Entity("WebApi.Models.TodoItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });
#pragma warning restore 612, 618
        }
    }
}
